### PR TITLE
Fix Volumes module

### PR DESCRIPTION
**Pull request by jankodera-ps**
##### SUMMARY
Fixes volumes module to be able to create, update and delete them.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
fusion_volume

##### ADDITIONAL INFORMATION
Volume logic did not wait for its operations and some arguments were incorrect. This PR fixes and cleans up the logic.
Several utility files are added and meant to be reused:
- module_utils/operations.py: has await_operation() which waits for asynchronous Fusion REST API Operation to complete before returning.
- module_utils/parsing.py: contains parsing and printing routines for human readable sizes like 43M, 22 G etc. These routines are duplicated among the modules and several parse corner cases wrong, so the intention is to eventually replace these with parsing.py which is unit tested and hopefully flexible enough.

### CODE REVIEW

**Review by sdodsley — CHANGES_REQUESTED** [review]
Don't modify `galaxy.yml` until we create a PR to create the new release

**Review by sdodsley — APPROVED** [review]

**Comment by sdodsley** [comment]
@jankodera-ps looks like a boilerplate requirement is missing.
Sadly we are still required to test against Ansible 2.11 for the time being

**Comment by jankodera-ps** [comment]
The boilerplate errors look like heisenbugs to me. It is complaining about missing
'__metaclass__ = type'
'from __future__ import (absolute_import, division, print_function)'
but I see them in the [file](https://github.com/jankodera-ps/Fusion-Collection/blob/jkodera/fix-fusion_volume_py/plugins/module_utils/parsing.py#L6).
Could I ask you to rerun the checks, please?

**Comment by sdodsley** [comment]
I agree that is weird. 
I'll have to raise this with the Ansible support team.

**Comment by sdodsley** [comment]
@jankodera-ps Thisis th emessage from Ansible engineering:

It looks like you need to add the import and `__metaclass__==type` statement to the unit test in [tests/unit/module_utils/parsing.py](https://github.com/Pure-Storage-Ansible/Fusion-Collection/pull/54/files#diff-c17506ed4b5c5bf9801afda62671bb5f64539e27d4340cf8c63610aff06d5b2a) file as well. It's not present in that file.

**Review by sdodsley — APPROVED** [review]

**Pull request merged**
